roasts = [
    "You're not stupid; you just have bad luck thinking.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "If I had a dollar for every smart thing you said, I’d be broke.",
    "You're the reason shampoo has instructions.",
    "You're as useless as the 'g' in lasagna.",
    "You bring everyone so much joy… when you leave the room.",
    "Your face makes onions cry.",
    "You have something on your chin… no, the third one down.",
    "You're not the dumbest person alive, but you better hope they don’t die.",
    "You're the human version of a participation trophy.",
    "Your secrets are safe with me. I never listen anyway.",
    "You're like a software update — every time I see you, I think 'Not now.'",
    "You're the reason the gene pool needs a lifeguard.",
    "You're like a Monday morning: nobody likes you and everyone wants you to go away.",
    "You're about as sharp as a marble.",
    "You bring everyone together — just so they can talk about you behind your back.",
    "You're not completely useless, you can still serve as a bad example.",
    "You're like a broken pencil — pointless.",
    "Your brain is like the Bermuda Triangle — information goes in, but it's never found again.",
    "You're so dense, black holes take notes.",
    "You're not ugly, but you make mirrors wish they had a snooze button.",
    "You're like a campfire — people gather around, but only to roast you.",
    "You're the WiFi signal of people: always weak and unreliable.",
    "You're proof evolution can go in reverse.",
    "You couldn’t pour water out of a boot with instructions on the heel.",
    "Your comebacks are like your grades — below average.",
    "You're the human embodiment of buffering.",
    "You're what happens when the mute button doesn't work IRL.",
    "You have something no one else has — my disappointment.",
    "You're like a math problem nobody wants to solve.",
    "You're a great example of why cousins shouldn’t marry.",
    "You're like expired milk — once useful, now just gross.",
    "You're about as helpful as a screen door on a submarine.",
    "You bring nothing to the table — not even a chair.",
    "You're a full-time job and no one applied.",
    "You're more disappointing than an unskippable YouTube ad.",
    "You're like if bad vibes became a person.",
    "You're the kind of person who trips over a wireless connection.",
    "You're the reason the dinosaurs gave up.",
    "You're so irrelevant, even your imaginary friends ghosted you.",
    "You're the main character — in a cautionary tale.",
    "You're more extra than the cheese I didn’t ask for.",
    "You're the loading screen of people — always there, never useful.",
    "You're less reliable than a McDonald's ice cream machine.",
    "You're more fake than Instagram filters.",
    "You're what happens when common sense takes a vacation.",
    "You're the human version of a 404 error.",
    "You're so boring, even Siri ignores you.",
    "You're like a selfie in bad lighting — unwanted and awkward.",
    "You're more toxic than Twitter at 2 AM.",
    "You're the dictionary definition of 'Why tho?'",
    "You're what auto-correct warns us about.",
    "You're the plot twist no one asked for.",
    "You're the human version of low battery.",
    "You're like a TikTok repost — we’ve all seen it and we’re not impressed.",
    "You're like Bluetooth — always around, rarely connects.",
    "You're less useful than a pencil with no lead.",
    "You're the DLC nobody downloaded.",
    "You're like a loading bar stuck at 99%.",
    "You're the unskippable part of a Spotify ad.",
    "You're the last pick in dodgeball — for both teams.",
    "You're like a laggy Zoom call in human form.",
    "You're the NPC who never got voiced.",
    "You're like a knock-off brand — just not quite right.",
    "You're the reason group projects fail.",
    "You're the person Clippy from Microsoft Word gave up on.",
    "You're the 'before' picture in every ad.",
    "You're the online friend no one wants to meet IRL.",
    "You're the crash report of social interactions.",
    "You're more confusing than IKEA instructions.",
    "You're like printer paper — blank and lifeless.",
    "You're like an expired coupon — useless and disappointing.",
    "You're the offline version of fun.",
    "You're the kind of cringe that gives others secondhand embarrassment.",
    "You're like an empty soda can — loud but hollow.",
    "You're the side quest everyone skips.",
    "You're the update that breaks everything.",
    "You're the captcha that no one can solve.",
    "You're like Internet Explorer — 10 years too late.",
    "You're like a dead meme — everyone moved on but you're still here.",
    "You're the person YouTube ads are targeted at.",
    "You're the person who brings a fork to a soup party.",
    "You're so slow, snails ask if you're okay.",
    "You're not even goofy — you're just glitchy.",
    "You're not built different — you're built defective.",
    "You're the “…” in people’s typing bubbles because they don’t know what to say to you.",
    "You're more extra than a group project overachiever — and still do nothing.",
    "You're like a recycled insult — still trash the second time.",
    "You're the background character who forgot their lines.",
    "You're more disappointing than a YouTube apology video.",
    "You're the IRL version of “low effort.”",
    "You're what people mean when they say 'unfunny but tries hard.'",
    "You're the human equivalent of a microwave beep — annoying and never on time.",
    "You're the walking version of lag.",
    "You're the reason 'read receipts' were invented — so people know not to reply.",
    "You're the pause button on a hype song.",
    "You're so fake, Barbie is jealous.",
    "You're the placeholder friend until someone cooler shows up.",
    "You're like a password hint that says 'password'.",
    "You're the 'terms and conditions' of friendships — no one reads you.",
    "You're the spam folder of people — always avoided.",
    "You're like a reboot that made the original look better.",
    "You're the plot hole in everyone's day."
]